Add calculator for number with arbitrary precision
thomashilke/KineticConvolution pull request #28
Opened 2022-06-01 09:50 UTC by TimotheePouchon

In this PR we introduce an implementation of `IAlgebraicNumberCalculator` relying on the numbers with arbitrary precision from [PeterO.Numbers](https://github.com/peteroupc/Numbers).

2022-06-29 10:50 UTC, thomashilke requested changes

2022-06-29 10:50 UTC, thomashilke commented on KineticConvolution.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Hilke.KineticConvolution.EFloatAlgebraicNumber", "src\Hilke.EFloatCalculator\Hilke.KineticConvolution.EFloatAlgebraicNumber.csproj", "{81BC3082-25
```suggestion
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Hilke.KineticConvolution.EFloatAlgebraicNumber", "src\Hilke.KineticConvolution.EFloatAlgebraicNumber\Hilke.KineticConvolution.EFloatAlgebraicNumber.csproj", "{81BC3082-2522-400C-998D-C644803C5384}"

```
The folder of the project is not named correctly

2022-06-29 10:50 UTC, thomashilke commented on src/Hilke.EFloatCalculator/EFloatAlgebraicNumberCalculator.cs
> +                    message: "Tolerance must be strictly positive.",
Strictly or not strictly? `.IsNegative` is `false` for 0, or not?

2022-06-29 10:50 UTC, thomashilke commented on src/Hilke.EFloatCalculator/Hilke.KineticConvolution.EFloatAlgebraicNumber.csproj
> +    <Description>Implementation of a calculator with arbitrary precision numbers.</Description>
```suggestion
    <Description>Implementation of a calculator with arbitrary precision arithmetic.</Description>
```

2022-06-29 10:50 UTC, thomashilke commented on src/Hilke.EFloatCalculator/EFloatAlgebraicNumberCalculator.cs
> +using System;
The folder is wrong, it should be called `Hilke.KineticConvolution.EFloatCalculator`

2022-06-29 10:50 UTC, thomashilke commented on tests/Hilke.EFloatCalculator.Tests/EFloatAlgebraicNumberCalculatorTests.cs
> +﻿using System;
The folder is wrong, it should be `Hilke.KineticConvolution.EFloatCalculator.Tests`

2022-07-10 15:59 UTC, Gimly commented
@thomashilke Je profite de ce PR ouvert pour (faire un petit coucou 😄 et) vous avertir que vous avez "Rollomatic" dans le début du namespace dans le fichier README.md ainsi que dans ce fichier https://github.com/thomashilke/KineticConvolution/blob/10170c822eb38af2f2232d95703f6599a06b2f94/samples/Hilke.KineticConvolution.ReadMeExamples/WorkingExample.cs.

2022-07-11 06:46 UTC, thomashilke commented
@Gimly Ouups bien vu, merci ^^ Bien le bonjour a toi! Petit spoiler: toute l'infrastructure de nombres algebriques qu'on a mise en place commence a bien porter ses fruit! ;)

2022-07-29 08:35 UTC, TimotheePouchon commented on KineticConvolution.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Hilke.KineticConvolution.EFloatAlgebraicNumber", "src\Hilke.EFloatCalculator\Hilke.KineticConvolution.EFloatAlgebraicNumber.csproj", "{81BC3082-25
all done

2022-07-29 08:38 UTC, TimotheePouchon commented on src/Hilke.EFloatCalculator/EFloatAlgebraicNumberCalculator.cs
> +                    message: "Tolerance must be strictly positive.",
It's not so clear in the doc :
`Gets a value indicating whether this object is negative, including negative zero.`
I explicitly excluded the zero.

2022-08-12 14:56 UTC, closed without merging